export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { at } = req.query
  if (!at) return res.status(400).json({ error: 'Missing token' })

  const spotifyHeaders = { 'Authorization': 'Bearer ' + at, 'Content-Type': 'application/json' }
  const anthropicKey = process.env.ANTHROPIC_API_KEY

  if (!anthropicKey) return res.status(500).json({ error: 'ANTHROPIC_API_KEY not configured' })

  try {
    const body = req.body
    const reviews = body.reviews || []
    const trackCount = Math.min(Math.max(reviews.length * 2, 6), 30)

    if (reviews.length === 0) return res.status(400).json({ error: 'No reviews provided' })

    // Build taste summary for Claude
    const tasteSummary = reviews.map(r => {
      const topTracks = (r.track_grades || [])
        .filter(t => t.grade && t.grade !== 'skipped' && t.score >= 87)
        .map(t => t.name)
        .slice(0, 3)
      return `"${r.album_name}" by ${r.album_artist} (scored ${r.final_score}/100)${topTracks.length ? ', top tracks: ' + topTracks.join(', ') : ''}`
    }).join('\n')

    // Ask Claude to recommend songs
    const claudeRes = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': anthropicKey,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 1024,
        messages: [{
          role: 'user',
          content: `You are a music expert. Based on this person's album reviews, recommend exactly ${trackCount} songs they would love.

Their reviews:
${tasteSummary}

Rules:
- Recommend songs similar in style, energy, and feel to their highly rated albums
- Include a mix of well-known and deeper cuts
- Vary the artists — don't repeat the same artist more than twice
- Return ONLY a JSON array, no other text, like this:
[{"artist": "Artist Name", "track": "Track Name"}, ...]

Return exactly ${trackCount} recommendations.`
        }]
      })
    })

    const claudeData = await claudeRes.json()
    if (!claudeRes.ok) return res.status(500).json({ error: 'Claude API error: ' + (claudeData.error?.message || 'unknown') })

    const claudeText = claudeData.content?.[0]?.text || ''
    let recommendations
    try {
      const jsonMatch = claudeText.match(/\[[\s\S]*\]/)
      recommendations = JSON.parse(jsonMatch ? jsonMatch[0] : claudeText)
    } catch {
      return res.status(500).json({ error: 'Could not parse recommendations' })
    }

    // Search each track on Spotify
    const trackUris = []
    for (const rec of recommendations) {
      try {
        const q = encodeURIComponent(rec.track + ' ' + rec.artist)
        const searchRes = await fetch('https://api.spotify.com/v1/search?q=' + q + '&type=track&limit=1&market=US', { headers: spotifyHeaders })
        if (searchRes.ok) {
          const searchData = await searchRes.json()
          const track = searchData.tracks?.items?.[0]
          if (track) trackUris.push(track.uri)
        }
      } catch {}
    }

    if (trackUris.length === 0) return res.status(500).json({ error: 'Could not find any tracks on Spotify' })

    // Get Spotify user
    const userRes = await fetch('https://api.spotify.com/v1/me', { headers: spotifyHeaders })
    const user = await userRes.json()
    if (!userRes.ok) return res.status(401).json({ error: 'Spotify auth expired — sign out and back in.' })

    // Find or create WAX Picks playlist
    const playlistsRes = await fetch('https://api.spotify.com/v1/me/playlists?limit=50', { headers: spotifyHeaders })
    const playlistsData = playlistsRes.ok ? await playlistsRes.json() : { items: [] }
    let playlist = (playlistsData.items || []).find(p => p.name === 'WAX Picks')

    if (!playlist) {
      const createRes = await fetch('https://api.spotify.com/v1/users/' + user.id + '/playlists', {
        method: 'POST', headers: spotifyHeaders,
        body: JSON.stringify({
          name: 'WAX Picks',
          description: 'Generated by WAX based on your taste profile.',
          public: true
        })
      })
      playlist = await createRes.json()
    }

    // Update playlist
    await fetch('https://api.spotify.com/v1/playlists/' + playlist.id + '/tracks', {
      method: 'PUT', headers: spotifyHeaders,
      body: JSON.stringify({ uris: trackUris })
    })

    return res.json({
      playlist_id: playlist.id,
      playlist_url: 'https://open.spotify.com/playlist/' + playlist.id,
      track_count: trackUris.length
    })

  } catch (e) {
    return res.status(500).json({ error: e.message || 'Unknown error' })
  }
}
